# Generated by Django 3.0 on 2019-12-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcoupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
