# Generated by Django 3.0 on 2019-12-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcoupon', '0002_auto_20191207_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='date_end',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
