# Generated by Django 3.0 on 2019-12-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcoupon', '0003_auto_20191217_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
