# Generated by Django 3.0 on 2019-12-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listcoupon', '0004_auto_20191217_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='voucher',
        ),
    ]
