# Generated by Django 3.0 on 2019-12-18 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listcoupon', '0005_auto_20191217_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 13, 45, 41, 371824), max_length=6),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='voucher',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
